import React, { useState } from 'react';
import { DecisionAnalysis } from '../types';
import { generateAndDownloadDecisionPdf } from '../utils/pdfGenerator';
import {
  X,
  Download,
  Copy,
  Check,
  FileText,
  Award,
  AlertCircle,
  Sparkles,
} from 'lucide-react';

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  decision: DecisionAnalysis;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  isOpen,
  onClose,
  decision,
}) => {
  const [copiedMemo, setCopiedMemo] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState<string | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  if (!isOpen) return null;

  const recommendedOpt =
    decision.options.find((o) => o.id === decision.recommendation?.recommendedOptionId) ||
    decision.options[0];

  const handleDownloadPdfDirect = () => {
    setErrorMessage(null);
    setIsGeneratingPdf(true);
    try {
      const success = generateAndDownloadDecisionPdf(decision);
      if (success) {
        setDownloadSuccess('Complete Decision PDF downloaded successfully!');
        setTimeout(() => setDownloadSuccess(null), 3000);
      } else {
        setErrorMessage('Could not generate PDF. Please try again or copy the text summary.');
      }
    } catch (e: any) {
      setErrorMessage('PDF download encountered an issue.');
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  // Generate clean text summary
  const generateMarkdownReport = (): string => {
    let md = `# DECISION SUMMARY: ${decision.title.toUpperCase()}\n\n`;
    md += `**Date:** ${new Date(decision.createdAt || Date.now()).toLocaleDateString()} | **Category:** ${decision.category || 'General'} | **Timeframe:** ${decision.timeHorizon || '1 year'} | **Undoable:** ${decision.reversibility || 'Somewhat reversible'}\n\n`;
    md += `---\n\n`;

    md += `## 1. YOUR QUESTION\n`;
    md += `> ${decision.originalPrompt || decision.title}\n\n`;

    md += `## 2. BEST CHOICE & RECOMMENDATION\n`;
    md += `### **You Should Choose: ${recommendedOpt?.title || 'Primary Choice'}**\n`;
    md += `*Confidence Level: ${decision.recommendation?.confidenceLevel || 'High'}*\n\n`;
    if (decision.recommendation?.mainReasons?.length) {
      md += `**Why this choice is best:**\n`;
      decision.recommendation.mainReasons.forEach((r) => {
        md += `- ${r}\n`;
      });
      md += `\n`;
    }

    if (decision.recommendation?.tradeOff || decision.recommendation?.bottomLine) {
      md += `**Key Trade-off:** ${decision.recommendation.tradeOff || decision.recommendation.bottomLine}\n\n`;
    }

    if (decision.recommendation?.biggestConcern) {
      md += `**Main Thing to Watch Out For:** ${decision.recommendation.biggestConcern}\n\n`;
    }

    md += `## 3. CHOICES COMPARED\n`;
    decision.options.forEach((opt, idx) => {
      md += `### Choice ${idx + 1}: ${opt.title}\n`;
      if (opt.description) md += `${opt.description}\n\n`;
    });

    if (decision.criteria && decision.criteria.length > 0) {
      md += `## 4. WHAT MATTERS MOST (SCORING)\n\n`;
      md += `| Factor | Importance | ${decision.options.map((o) => o.title).join(' | ')} |\n`;
      md += `| :--- | :---: | ${decision.options.map(() => ':---:').join(' | ')} |\n`;

      decision.criteria.forEach((crit) => {
        const rowScores = decision.options
          .map((opt) => `${decision.weightedScores?.[opt.id]?.[crit.id] ?? '-'} / 10`)
          .join(' | ');
        md += `| ${crit.name} | ${crit.weight}% | ${rowScores} |\n`;
      });
      md += `\n`;
    }

    if (decision.risks && decision.risks.length > 0) {
      md += `## 5. RISKS & HOW TO HANDLE THEM\n\n`;
      decision.risks.forEach((r) => {
        const opt = decision.options.find((o) => o.id === r.optionId);
        md += `- **[${r.probability} Likelihood]** for *${opt?.title || 'General'}*: ${r.risk}\n`;
        if (r.mitigation) md += `  - *How to handle:* ${r.mitigation}\n`;
      });
      md += `\n`;
    }

    md += `---\n`;
    md += `*Generated by Tiebreaker Studio*\n`;
    return md;
  };

  const handleCopyMarkdown = () => {
    const md = generateMarkdownReport();
    navigator.clipboard.writeText(md);
    setCopiedMemo(true);
    setTimeout(() => setCopiedMemo(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-stone-900/60 backdrop-blur-xs animate-fadeIn">
      <div className="skeuo-modal-shell max-w-lg w-full max-h-[90vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#E0D9CC] bg-[#FAF7F2]">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl skeuo-btn-primary text-white flex items-center justify-center">
              <Download className="w-4 h-4 text-[#D4A338]" />
            </div>
            <div>
              <h3 className="font-serif italic text-base font-bold text-stone-900">
                Save as PDF Report
              </h3>
              <p className="text-[11px] text-stone-500">
                Download your complete decision analysis as a high-quality PDF.
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg text-stone-400 hover:text-stone-700 hover:bg-stone-200/50 transition-colors cursor-pointer"
            aria-label="Close"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 space-y-5 overflow-y-auto flex-1 text-xs">
          {/* Overview Preview */}
          <div className="p-4 rounded-xl skeuo-well space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-[10px] font-bold uppercase tracking-wider text-[#B88E3D] flex items-center gap-1.5">
                <Award className="w-3.5 h-3.5 text-[#B88E3D]" /> Report Summary
              </span>
              <span className="text-[10px] text-stone-500 font-mono">
                {decision.options.length} Choices Analyzed
              </span>
            </div>
            <h4 className="text-sm font-serif italic text-stone-900 font-bold">
              {decision.title}
            </h4>
            <p className="text-stone-700 leading-relaxed font-sans">
              <strong>Best Choice:</strong> You should choose{' '}
              <strong className="text-[#B88E3D]">{recommendedOpt?.title}</strong> ({decision.recommendation?.confidenceLevel || 'High'} confidence).
            </p>
          </div>

          {/* Action Cards */}
          <div className="space-y-3">
            {/* Primary Action: Direct Complete PDF Download */}
            <button
              type="button"
              onClick={handleDownloadPdfDirect}
              disabled={isGeneratingPdf}
              className="w-full flex items-start gap-3.5 p-4 rounded-xl skeuo-card border-2 border-amber-300/80 bg-amber-50/50 hover:bg-amber-50 hover:border-[#B88E3D] transition-all text-left group cursor-pointer shadow-xs"
            >
              <div className="p-3 rounded-xl bg-[#B88E3D] text-white shrink-0 shadow-xs">
                <Download className="w-5 h-5" />
              </div>
              <div className="space-y-1 flex-1">
                <div className="flex items-center justify-between">
                  <span className="font-bold text-stone-900 text-xs sm:text-sm group-hover:text-[#B88E3D]">
                    {isGeneratingPdf ? 'Generating PDF...' : 'Download Decision PDF (.pdf)'}
                  </span>
                  <span className="px-2 py-0.5 rounded text-[9px] font-bold bg-[#B88E3D] text-white">
                    Complete Report
                  </span>
                </div>
                <p className="text-[11px] text-stone-600 leading-relaxed">
                  Includes recommendation, scoring matrix, pros & cons, risks, and scenario timelines.
                </p>
              </div>
            </button>

            {/* Secondary Action: Copy Summary Text */}
            <button
              type="button"
              onClick={handleCopyMarkdown}
              className="w-full flex items-start gap-3.5 p-3.5 rounded-xl skeuo-card hover:border-[#B88E3D] transition-all text-left group cursor-pointer"
            >
              <div className="p-2.5 rounded-lg bg-stone-100 border border-stone-300 text-stone-700 shrink-0">
                {copiedMemo ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
              </div>
              <div className="space-y-0.5">
                <span className="font-bold text-stone-900 block text-xs group-hover:text-[#B88E3D]">
                  {copiedMemo ? 'Copied to Clipboard!' : 'Copy Text Summary'}
                </span>
                <p className="text-[11px] text-stone-500 leading-relaxed">
                  Quick text summary to paste into messages, notes, or emails.
                </p>
              </div>
            </button>
          </div>

          {downloadSuccess && (
            <div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs flex items-center gap-2 font-medium">
              <Check className="w-4 h-4 text-emerald-600" />
              <span>{downloadSuccess}</span>
            </div>
          )}

          {errorMessage && (
            <div className="p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-xs flex items-center gap-2 font-medium">
              <AlertCircle className="w-4 h-4 text-red-600" />
              <span>{errorMessage}</span>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-3.5 border-t border-[#E0D9CC] bg-[#FAF7F2] flex items-center justify-between">
          <span className="text-[10px] text-stone-500">
            Tiebreaker Studio
          </span>
          <button
            type="button"
            onClick={onClose}
            className="px-5 py-2 rounded-xl skeuo-btn-secondary text-stone-800 text-xs font-bold transition-colors cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
